### ISSUE TITLE
Get rid of python2 dependency

### ISSUE THREAD

**Issue by georgkrause** [unikubehq/docs#37]
When I try to install the dependencies for the documentation, I get the following issue:

```
npm ERR! code 1
npm ERR! path /home/georg/workspace/blueshoe/docs/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /home/georg/workspace/blueshoe/docs/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/home/georg/workspace/blueshoe/docs/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.7.1 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/georg/workspace/blueshoe/docs/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/georg/workspace/blueshoe/docs/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/georg/workspace/blueshoe/docs/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/georg/workspace/blueshoe/docs/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/georg/workspace/blueshoe/docs/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/georg/workspace/blueshoe/docs/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/georg/workspace/blueshoe/docs/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/georg/workspace/blueshoe/docs/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/georg/workspace/blueshoe/docs/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/georg/workspace/blueshoe/docs/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/georg/workspace/blueshoe/docs/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/georg/workspace/blueshoe/docs/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /home/georg/.pyenv/shims/python
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /home/georg/.pyenv/shims/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Linux 5.10.105-1-MANJARO
npm ERR! gyp ERR! command "/usr/bin/node" "/home/georg/workspace/blueshoe/docs/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/georg/workspace/blueshoe/docs/node_modules/node-sass
npm ERR! gyp ERR! node -v v17.7.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1
```

Problem seems to be that I don't have python2 installed. The problem seems to be `vuepress-plugin-element-tabs`, which depends on the deprecated node-sass.

**Comment by georgkrause** [comment]
Funfact: If it was once installed successfully with Node 14.19.1, `npm install` also works fine when using later versions

**Comment by tobifroe** [comment]
@georgkrause I changed the dependency responsible for rendering the tabs, node-sass isn't needed anymore.
